# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: generate_modlist_from_save.py
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-docstring-first

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.3.0'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0  # pick a git hash / tag to point to
    hooks:
      - id: pydocstyle
        exclude: "test_*"
        args: ["--convention=numpy"]
